# Generated by Django 5.0.6 on 2024-07-22 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quisition', '0002_rename_quisitionmodel_quisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='quisition',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
