# Generated by Django 5.0.6 on 2024-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quisition', '0006_quisition_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='quisition_like',
            name='status',
            field=models.CharField(choices=[('dislike', 'Dislike'), ('like', 'Like')], default=2, max_length=7),
            preserve_default=False,
        ),
    ]
