# Generated by Django 5.0.6 on 2024-07-27 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_like',
            name='status',
            field=models.CharField(choices=[('dislike', 'Dislike'), ('like', 'Like')], default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
